# Generated by Django 2.1.2 on 2018-10-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippngAddress1',
            new_name='shippingAddress1',
        ),
        migrations.AddField(
            model_name='order',
            name='shippingCity',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
